webapp:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/ingress.class: nginx
    hosts:
    - host: airbyte.k8s.example.com
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls:
    - hosts:
      - airbyte.k8s.example.com
      secretName: airbyte-tls

postgresql:
  enabled: false

externalDatabase:
  host: pg-release-postgresql
  user: airbyte
  password: airbyte
  database: airbyte

# https://github.com/airbytehq/airbyte/issues/11157#issuecomment-1927515718
temporal:
  extraEnv:
    - name: SKIP_DB_CREATE
      value: "true"
