# values/superset.yml
configOverrides:
  secret: |
    SECRET_KEY = '<generated secret, e.g. `openssl rand -base64 42`>'
  examples_config: |
    SQLALCHEMY_EXAMPLES_URI = 'postgresql://superset:superset@pg-release-postgresql:5432/examples?options=-csearch_path%3Ddbo,main'

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: nginx
  hosts:
  - superset.k8s.example.com
  tls:
  - hosts:
    - superset.k8s.example.com
    secretName: superset-tls

init:
  loadExamples: true

postgresql:
  enabled: false

supersetNode:
  connections:
    db_host: 'pg-release-postgresql'
