---
- name: Add Docker CE Repo
  become: true
  ansible.builtin.apt_repository:
    filename: docker
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
- name: Install Docker CE
  become: true
  ansible.builtin.apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
    state: present
    update_cache: true
- name: Start & Enable Docker
  become: true
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
- name: Start & Enable Docker-containerd
  become: true
  ansible.builtin.systemd:
    name: containerd
    state: started
    enabled: true

# User stuff
# TODO: convert to host variable(s)
- name: Give "c" user Docket management rights
  become: true
  ansible.builtin.user:
    name: c
    groups: docker
    append: yes

# TODO: consider/look at implementing https://docs.docker.com/engine/security/rootless/#prerequisites
# TODO: consider/look at using the snap instead: https://snapcraft.io/docker
