---
# Ensure hostname is correct (and has full FQDN)
# Note: this does not account for all cases (e.g. /etc/hosts, particularly if cloud-init generates the file)
- name: Ensure hostname is correct and is the full FQDN
  become: true
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
- name: "Force DNS servers, if requested, via config"
  become: true
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf.tail
    owner: root
    group: root
    mode: '0644'
  when: "resolv_force_dns is defined and resolv_force_dns is truthy"
- name: "Force DNS servers, if requested, one-off"
  become: true
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    line: 'nameserver {{ resolv_force_dns }}'
    state: present
  when: "resolv_force_dns is defined and resolv_force_dns is truthy"

# Base packages to ensure exist
- include_tasks: packages.yml

# Get groups
#- name: Get available groups
#  become: true
#  ansible.builtin.getent:
#    database: group
#    split: ":"
#- ansible.builtin.debug:
#    var: "ansible_facts.getent_group|dict2items|map(attribute='key')"

# Create/delete/update user accounts
- include_tasks: users.yml
  loop: "{{ lookup('community.general.merge_variables', '^users(_.+)?$', initial_value=[]) }}"
  loop_control:
    loop_var: user
    label: "{{ user.username }}"
# Disable root account (only allow root access via sudo)
- name: Ensure root account is locked
  become: true
  ansible.builtin.user:
    name: root
    password: '*'
# Delete any default accounts used by hosts for provisioning
- name: Delete any default accounts used for provisioning
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    state: absent
  loop:
  - ubuntu
  - debian

# Conditional packages
- include_tasks: unattended.yml
  when: "unattended_upgrades is defined and unattended_upgrades is truthy"

# Other conditional configurations
- name: Configure cron jobs
  become: true
  ansible.builtin.cron: "{{ cron_item }}"
  loop: "{{ cron }}"
  loop_control:
    loop_var: cron_item
    label: "{{ cron_item.name }}"
  when: "cron is defined and cron is truthy"

# Misc
- name: Configure Git initial branch name
  become: true
  community.general.git_config:
    name: init.defaultBranch
    scope: system
    value: main
