---
# Nvidia structures its CUDA repos using a string formatted as <distro>/<arch>
# This string is also needed to install the cuda-keyring, which manages
# the repo's GPG key & apt source.
#
# If a configuration string isn't passed (e.g. with host vars), then
# the playbook will attempt to guess it. If it can't guess correctly,
# you'll need to specify it manually.
#
# You can see the repos here: https://developer.download.nvidia.com/compute/cuda/repos/
# CUDA Installation Guide for Linux: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/
#
# TODO list:
# * Allow specifying CUDA versions (e.g. specifying 12.2 to install cuda-12-2)
# * CUDA appears to manage the driver version and install the correct kernel
#   headers - need to verify this is true.
#
# Notes:
# * For RHEL, you'd want ansible_distribution_major_version instead of ansible_distribution_version
- name: Print Nvidia distro/arch string if set
  ansible.builtin.debug:
    msg: "Found Nvidia distro/arch string: {{ nvidia_distro_arch }}"
  when: "nvidia_distro_arch is defined"
- name: Guess Nvidia distro/arch string
  ansible.builtin.debug:
    msg: "Nvidia distro/arch string not set; guessing: {{ [ansible_distribution|lower,ansible_distribution_version|replace('.',''),'/',ansible_architecture]|join('') }}"

# Remove outdated keys
- name: Ensure Nvidia outdated signing keys are not present
  become: true
  ansible.builtin.apt_key:
    # TODO key IDs
    state: absent

# CUDA
- name: Ensure cuda-keyring is installed (manages repo)
  become: true
  ansible.builtin.apt:
    deb: "https://developer.download.nvidia.com/compute/cuda/repos/{{ nvidia_distro_arch | default([ansible_distribution|lower,ansible_distribution_version|replace('.',''),'/',ansible_architecture]|join('')) }}/cuda-keyring_1.1-1_all.deb"
  when: "'cuda-keyring' not in ansible_facts.packages"
- name: Ensure CUDA is installed
  become: true
  ansible.builtin.apt:
    name: cuda
    state: present
    update_cache: true

# Container Runtime
# https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html
- name: Add Nvidia Container Toolkit Repo
  become: true
  ansible.builtin.apt_repository:
    filename: nvidia-container-toolkit
    repo: "deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit.gpg] https://nvidia.github.io/libnvidia-container/stable/deb/$(ARCH) /"
- name: Ensure CUDA is installed
  become: true
  ansible.builtin.apt:
    name: cuda
    state: present
    update_cache: true
