---
- name: Update all packages & autoremove old packages
  become: true
  ansible.builtin.apt:
    name: "*"
    autoremove: true
    state: latest
    update_cache: true
- name: Install common packages
  become: true
  ansible.builtin.apt:
    state: present # Some of these are "duh" but I've had random packages missing on various distros so...
    name:
    - apt-transport-https
    - bash
    - ca-certificates
    - curl
    - git
    - less
    #- mtr-tiny # Don't enable on server, requires SUID binary
    - nano
    - sudo
    - tmux
    - wget
- name: Remove unneeded packages
  become: true
  ansible.builtin.apt:
    state: absent
    name:
    - pastebinit
- name: Check if reboot needed
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_checksum: no
  register: stat_reboot_required
- name: Reboot
  become: true
  when: stat_reboot_required.stat.exists
  ansible.builtin.reboot:
    msg: Rebooting to finish system updates
