# manifests/cert-manager-issuer.yml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: <let's encrypt email>
    privateKeySecretRef:
      name: prod-issuer-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - selector: {}
      dns01:
        cloudflare:
          email: <cloudflare email>
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
