---
- name: restart_fpm
  become: true
  ansible.builtin.systemd:
    name: php{{ item }}-fpm
    state: restarted
  loop: "{{ php_versions }}"
- name: reload_nginx
  become: true
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
