- name: Default deny incoming connections
  become: true
  community.general.ufw:
    default: deny
    direction: incoming
  notify: reload_ufw

- name: Allow SSH
  become: true
  community.general.ufw:
    rule: allow
    direction: in
    name: OpenSSH

#- name: Make sure that there isn't a rule allowing SSH from anywhere
#  become: true
#  community.general.ufw:
#    delete: true
#    rule: allow
#    direction: in
#    name: OpenSSH

- name: Ensure UFW is enabled
  become: true
  community.general.ufw:
    state: enabled
