---
- name: SSH - Prohibit empty passwords
  become: true
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "PermitEmptyPasswords no"
    regexp: '^PermitEmptyPasswords '
    insertafter: '#PermitEmptyPasswords'
- name: SSH - Enable Logging
  become: true
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "LogLevel INFO"
    regexp: '^LogLevel '
    insertafter: '#LogLevel'
- name: SSH - Enable Pubkey Authentication
  become: true
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "PubkeyAuthentication yes"
    regexp: '^PubkeyAuthentication '
    insertafter: '#PubkeyAuthentication'
- name: SSH - Disable root login
  become: true
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "PermitRootLogin no"
    regexp: '^PermitRootLogin '
    insertafter: '#PermitRootLogin'
